Update keymap.c
1) COMENTAR LA LINEA

	//#define IGNORE_MOD_TAP_INTERRUPT

	- Compiling: quantum/action_tapping.c                                                                
					quantum/action_tapping.c:15:10: error: #error 
					"IGNORE_MOD_TAP_INTERRUPT is no longer necessary as it is now the default behavior of mod-tap keys.
					Please remove it from your config."
					
2) ASIGNAR NOMBRE AL TIPO DE LAYOUT

3) TECLA RESET -> QK_BOOT
4) TECLAS: 	KC__MUTE -> KC_MUTE
			KC__VOLUP -> KC_VOLU
			KC__VOLDOWN -> KC_VOLD
			
5) ELIMINAR PREFIJO qk_
	qk_tap_dance_action_t -> tap_dance_action_t
	- Prefix qk_ removed -> Pull Request https://github.com/qmk/qmk_firmware/pull/19313